name: build-deploy

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: touch /tmp/file.txt

      - name: Save Docker image as tar file
        run: ls /tmp
        
      - name: Transfer Docker image to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 54.236.225.174
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: tmp/file.txt
          target: "/home/ubuntu"
          debug: true
