name: build-deploy

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -f ./Dockerfile -t laniakea-group/prometei-rest-api:${{ github.sha }}

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker stop prometei-rest-api || true
            sudo docker rm prometei-rest-api || true
            sudo docker pull laniakea-group/prometei-rest-api:${{ github.sha }}
            sudo docker run -d --name=prometei-rest-api -p 80:80 laniakea-group/prometei-rest-api:${{ github.sha }}
